### ISSUE TITLE
"127.0.0.1 n'autorise pas la connexion"

### ISSUE THREAD

**Issue by Paulcou** [adaltas/ece-2020-fall-webtech-project#1]
Hi Mr,
Our application compiles and works but when we want to connect with OAuth, we arrive on a page with the error written in the title. It has worked once or twice so it's reaaly weird but atleast we know the dex config is good.
Do you have a solution? (We tried to remove proxies and friewalls but same result).
Thank you

**Comment by wdavidw** [comment]
Please be more procise about the the context. For example, what is the exact URL, which browser, is the message displayed by the Dex server ?

**Comment by Paulcou** [comment]
The url is the one when we click one "Login with OAuth..." : "http://127.0.0.1:5556/dex/auth?client_id=webtech-frontend&s...."
It happens on chrome but also on firefox.
It is displayed by the browser.
Thanks

**Comment by wdavidw** [comment]
What is the output of `curl -L -v http://127.0.0.1:5556/dex/.well-known/openid-configuration`

**Comment by Paulcou** [comment]
*   Trying 127.0.0.1:5556...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5556 (#0)
> GET /dex/.well-known/openid-configuration HTTP/1.1
> Host: 127.0.0.1:5556
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 1031
< Content-Type: application/json
< Date: Tue, 08 Dec 2020 09:35:37 GMT
<
{
  "issuer": "http://127.0.0.1:5556/dex",
  "authorization_endpoint": "http://127.0.0.1:5556/dex/auth",
  "token_endpoint": "http://127.0.0.1:5556/dex/token",
  "jwks_uri": "http://127.0.0.1:5556/dex/keys",
  "userinfo_endpoint": "http://127.0.0.1:5556/dex/userinfo",
  "device_authorization_endpoint": "http://127.0.0.1:5556/dex/device/code",
  "grant_types_supported": [
    "authorization_code",
    "refresh_token",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "response_types_supported": [
    "code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "code_challenge_methods_supported": [
    "S256",
    "plain"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic"
  ],
  "claims_supported": [
    "aud",
    "email",
    "email_verified",
    "exp",
    "iat",
    "iss",
    "locale",
    "name",
    "sub"
  ]
* Connection #0 to host 127.0.0.1 left intact

**Comment by wdavidw** [comment]
GitHub issues must respect the markdown format, you can click "preview" and refer to any markdown documentation (it is a very small set of conventions). Please edit your comment above and modify it accordingly.

**Comment by wdavidw** [comment]
Dex is working and listening on `127.0.0.1:5556`. Did you update the dex server configuration to reflect your settings ?

**Comment by Paulcou** [comment]
I modified my last comment but I'm not sure that's what you wanted.
And yes, I updated the dex server configuration with my github settings.

**Comment by Paulcou** [comment]
Can I try to use passport.js ?

**Comment by wdavidw** [comment]
Passport can not work, it implies that the authentication is on the server which is not compatible with our microservice architecture (or way more complex). Go to the [course repository](https://github.com/adaltas/ece-2020-fall-webtech) there are to issues, adaltas/ece-2020-fall-webtech#12 and adaltas/ece-2020-fall-webtech#13, which share similar problems and their corrections

**Comment by wdavidw** [comment]
It just means that your front-end application is not started (or not started on port 3000 which I doubt).

**Comment by wdavidw** [comment]
Did you solve your issue? Don't forget to close it if so.

**Comment by Paulcou** [comment]
Not yet but I wasn't working on it today. Yes I will.

**Comment by Paulcou** [comment]
I changed of OS from WSL2 to Mac OS and now it works.
