### ISSUE TITLE
How to get username in the TokenID ?

### ISSUE THREAD

**Issue by MathieuDC** [adaltas/ece-2020-fall-webtech-project#3]
According to [the documentation](https://dexidp.io/docs/id-tokens/), it seems that our Dex server is supposed to send us the user name in the Token ID. Moreover, when running, our Dex server prints the user name in the log when a new connection is established, so we know that our Dex server has it. 

Nevertheless, when we print the Token ID that our Dex server sent us, we get this result : 
```javascript
{
  iss: 'http://127.0.0.1:5556/dex',
  sub: 'Cgg0MzM0NTkXXXXXXXXX',
  aud: 'webtech-frontend',
  exp: 1607859709,
  iat: 1607773309,
  at_hash: 'TWr2mx1rdYRXXXXXXXX',
  email: 'XXXXXXXX@gmail.com',
  email_verified: true
}
```
We can see that the username is now missing. 

I tried to look at the documentation but I didn't find anything. 

Can you give me the appropriate documentation link if I missed something or tell me what configurations are required to resolve this ?

**Comment by wdavidw** [comment]
Searching for username on the provided documentation url doesn't lead to any result. The identity of your user his is email, not his username.
